In [2]:
import numpy as np


In [5]:
random_generator = np.random.default_rng()

low = 0
high = 10
size = (5,8)
two_d_array = random_generator.uniform(low,high,size)
two_d_array


array([[0.61284214, 6.29964538, 6.03950453, 3.2211586 , 2.98949791,
        4.82625345, 9.05954075, 3.43681287],
       [9.31814085, 1.67904327, 6.58921827, 5.19327422, 3.63994856,
        9.48822233, 4.62335322, 8.10528478],
       [6.69598877, 2.26505399, 2.69460818, 8.19791714, 9.80481234,
        0.53375658, 9.15208036, 4.18222108],
       [4.53146125, 5.12949844, 1.50203726, 5.46599149, 6.15758714,
        9.01372034, 3.11499701, 9.67819224],
       [2.01511316, 1.05468309, 3.68904313, 6.69899771, 3.2804476 ,
        4.43271536, 0.52432347, 7.63278282]])

In [8]:
filas = [0,4]
columnas = [0,7]
two_d_array[filas,columnas]


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [5]:
np.zeros((10,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.ones(shape=(5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.empty((3,4),dtype=bool)

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
random_seed = np.random.default_rng(234)
random_array = random_seed.uniform(0,10, (10,8))
random_array

array([[8.00420346, 4.50835866, 2.81878459, 2.98685054, 5.01913723,
        7.58550555, 8.55751162, 1.75347781],
       [4.52705293, 6.50708712, 9.97521137, 8.69592359, 1.72987548,
        6.17977727, 8.62572151, 5.33497326],
       [0.24876897, 9.23306563, 5.34397035, 7.61873544, 9.37092355,
        3.71867816, 3.13380966, 1.89991334],
       [9.96638317, 5.75162585, 8.31149546, 0.18128841, 1.79191376,
        1.10371108, 6.75104258, 4.77263696],
       [6.21520918, 9.5161338 , 6.88358963, 0.79882468, 9.85136106,
        0.44815996, 8.72038396, 5.29391278],
       [8.08520117, 0.82528718, 6.73308055, 9.31990305, 8.87380773,
        6.33158932, 2.55039722, 4.38583917],
       [1.80937908, 9.79770925, 1.78568384, 4.9934576 , 2.66772572,
        7.96654025, 2.01173725, 2.16721259],
       [0.12440377, 3.23164298, 0.91057928, 8.57229133, 5.66165875,
        3.99869536, 2.17545526, 8.58258091],
       [8.14496662, 4.43855576, 8.62272716, 5.53912451, 5.72304774,
        9.82836647, 2.684673

In [53]:
random_array[-1,-1]

9.388840179923161

In [58]:
cinco= np.arange(5)
cinco

array([0, 1, 2, 3, 4])

In [59]:
cinco + 10

array([10, 11, 12, 13, 14])

In [60]:
cinco + [1,0,0,0,0]

array([1, 1, 2, 3, 4])

In [63]:
unos = np.ones((5,5),int)
unos

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
cinco + np.ones((5,5),int)

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [64]:
cinco.reshape(5,1) + unos

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [70]:
np.arange(3) + [[1,2,3],[4,5,6]]

array([[1, 3, 5],
       [4, 6, 8]])

In [71]:
import pandas as pd


In [75]:
pd.Series({2:'a',3:'b',1:"c"}, index=[4])

4    NaN
dtype: object

In [76]:
%pwd


'C:\\Users\\alejo\\dh\\notebooks'

In [86]:
df = pd.read_csv(r'C:\Users\alejo\dh\notebooks\clase_04\dsad_2021\M1\CLASE_04_EstadisticaDescriptiva\Data\bottle_reducido.csv',delimiter='\t', index_col='Sta_ID')
df

Depth_ID  Depthm  T_degC  O2Sat  \
Sta_ID                                                                       
044.0 048.5  19-4904CR-HY-087-0606-04400485-0000B-3       0   10.30   92.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0006A-3       6   18.46  111.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0010A-7      10   10.29   95.0   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0015A-3      15   10.29   95.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0020A-7      20   10.33   95.1   
...                                             ...     ...     ...    ...   
036.7 115.0  19-4911BD-HY-318-2130-03671150-0921A-3     921    3.91    4.8   
036.7 115.0  19-4911BD-HY-318-2130-03671150-1000A-7    1000    3.73    5.4   
036.7 115.0  19-4911BD-HY-318-2130-03671150-1100A-7    1100    3.51    6.4   
036.7 115.0  19-4911BD-HY-318-2130-03671150-1200A-7    1200    3.29    7.3   
036.7 115.0  19-4911BD-HY-318-2130-03671150-1247A-3    1247    3.18    7.6   

             Salnty  
Sta_ID               
044.0 048.5  33.030  
044.0 048.5  32.920  
044.0 048.5  32.951  
044.0 048.5  32.990  
044.0 048.5  33.005  
...             ...  
036.7 115.0  34.370  
036.7 115.0  34.401  
036.7 115.0  34.440  
036.7 115.0  34.481  
036.7 115.0  34.500  

[774 rows x 5 columns]

In [99]:
df.groupby('Sta_ID').mean()['Depthm'].round(2).to_frame(name='Average')

Average
Sta_ID              
036.7 115.0   355.60
039.0 096.0   352.82
041.0 077.0   336.20
042.0 068.0   337.52
044.0 048.5   238.18

In [97]:
mask = df.index == '044.0 048.5'
df[mask]

Depth_ID  Depthm  T_degC  O2Sat  \
Sta_ID                                                                       
044.0 048.5  19-4904CR-HY-087-0606-04400485-0000B-3       0   10.30   92.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0006A-3       6   18.46  111.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0010A-7      10   10.29   95.0   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0015A-3      15   10.29   95.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0020A-7      20   10.33   95.1   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0030A-7      30   10.39   94.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0031A-3      31   10.40   94.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0047A-3      47   10.36   91.1   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0050A-7      50   10.35   90.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0064A-3      64   10.25   88.1   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0075A-7      75   10.05   79.5   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0098A-3      98    9.54   59.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0100A-7     100    9.50   58.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0125A-7     125    9.05   49.2   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0132A-3     132    8.93   47.5   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0150A-7     150    8.66   41.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0197A-3     197    8.04   26.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0200A-7     200    8.01   26.2   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0250A-7     250    7.53   17.7   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0300A-7     300    7.11   11.9   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0382A-3     382    6.55    8.3   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0400A-7     400    6.41    8.1   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0500A-7     500    5.66    6.8   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0569A-3     569    5.20    6.1   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0600A-7     600    5.06    6.0   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0700A-7     700    4.60    5.7   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0800A-7     800    4.14    5.5   
044.0 048.5  19-4904CR-HY-087-0606-04400485-0818A-3     818    4.06    5.5   

             Salnty  
Sta_ID               
044.0 048.5  33.030  
044.0 048.5  32.920  
044.0 048.5  32.951  
044.0 048.5  32.990  
044.0 048.5  33.005  
044.0 048.5  33.054  
044.0 048.5  33.060  
044.0 048.5  33.150  
044.0 048.5  33.167  
044.0 048.5  33.260  
044.0 048.5  33.381  
044.0 048.5  33.640  
044.0 048.5  33.656  
044.0 048.5  33.810  
044.0 048.5  33.840  
044.0 048.5  33.891  
044.0 048.5  33.960  
044.0 048.5  33.966  
044.0 048.5  34.058  
044.0 048.5  34.136  
044.0 048.5  34.230  
044.0 048.5  34.232  
044.0 048.5  34.232  
044.0 048.5  34.220  
044.0 048.5  34.241  
044.0 048.5  34.313  
044.0 048.5  34.386  
044.0 048.5  34.400

In [118]:
lista= [0,1,2,3,4,5,6,7,8,9]
lista1= [i for i in range(10,20)]
lista2= [i for i in range(20,30)]

data = pd.DataFrame([lista,lista1,lista2], columns=[[f'col {i}' for i in range(0,10)]])
data


col 0 col 1 col 2 col 3 col 4 col 5 col 6 col 7 col 8 col 9
0     0     1     2     3     4     5     6     7     8     9
1    10    11    12    13    14    15    16    17    18    19
2    20    21    22    23    24    25    26    27    28    29

In [105]:
data == 0

0      1      2      3      4      5      6      7      8      9
0   True  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False

In [107]:
data.isin([0])

0      1      2      3      4      5      6      7      8      9
0   True  False  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False  False  False

In [117]:
data.iloc[:,:-1]

0   1   2   3   4   5   6   7   8
0   0   1   2   3   4   5   6   7   8
1  10  11  12  13  14  15  16  17  18
2  20  21  22  23  24  25  26  27  28

In [137]:
mask1 = data['col 6'] >10

data[mask1]

TypeError: only integer scalar arrays can be converted to a scalar index

In [129]:
data.count()

col 0    3
col 1    3
col 2    3
col 3    3
col 4    3
col 5    3
col 6    3
col 7    3
col 8    3
col 9    3
dtype: int64

In [3]:
array= np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
mask= array > 5
array[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
mask_a = array<5
mask_b = not ()
mask = np.logical_not(np.logical_or(mask_a,mask_b))
array[mask]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
import pandas as pd

In [19]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [20]:
data.loc[['a','d']]

a    0.25
d    1.00
dtype: float64

In [21]:
mask = np.logical_or(data.index == 'a', data.index == 'd')
data.loc[mask]

a    0.25
d    1.00
dtype: float64

In [22]:

mask = [x in ['a', 'd'] for x in data.index]
data.loc[mask]

a    0.25
d    1.00
dtype: float64

In [23]:
data[['a', 'd']]

a    0.25
d    1.00
dtype: float64

In [24]:
data['a', 'd']

KeyError: 'key of type tuple not found and not a MultiIndex'

In [30]:
df= pd.DataFrame([[1,3,5,8],[10,12,18,21],[9,4,0,78]])
df = df.T
df

0   1   2
0  1  10   9
1  3  12   4
2  5  18   0
3  8  21  78

In [32]:

mask1 = (df % 2 == 0)
data_pares = df[mask1]
mask2 = (df < 50)
data_pares[mask2]

0     1    2
0  NaN  10.0  NaN
1  NaN  12.0  4.0
2  NaN  18.0  0.0
3  8.0   NaN  NaN

In [33]:
mask1 = (df % 2 == 0)
mask2 = (df < 50)
mask = np.logical_and(mask1, mask2)
df[mask]

0     1    2
0  NaN  10.0  NaN
1  NaN  12.0  4.0
2  NaN  18.0  0.0
3  8.0   NaN  NaN

In [34]:
mask1 = (df % 2 == 0)
mask2 = (df < 50)
mask = np.logical_and(mask1, mask2)
df.loc[mask]

ValueError: Cannot index with multidimensional key

Hola soy marcela
