In [2]:
%run "../../../common/0_notebooks_base_setup.py"    

/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021_paula/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data


## Ejercicio 1
Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [27]:
import numpy as np

# local:
data_location = '../Data/sales_data_sample_excercise.csv'


In [30]:
data_type_default = np.genfromtxt(data_location, skip_header=1, delimiter='\t',dtype=str)
data_type_default

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [38]:
data_type_int = np.genfromtxt(data_location, skip_header=1, delimiter='\t',dtype=int)

In [39]:
data_type_float= np.genfromtxt(data_location, skip_header=1, delimiter='\t',dtype=float)

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [64]:
sales_str = data_type_default[:,1]
sales = sales_str.astype(np.float)
sales

array([2871.  , 2765.9 , 3884.34, ..., 5417.57, 2116.16, 3079.44])

In [42]:
country = data_type_default[:,5]
country

array(['USA', 'France', 'France', ..., 'Spain', 'France', 'USA'],
      dtype='<U16')

## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

In [68]:
minimo = np.min(sales)
minimo

482.13

In [67]:
maximo = np.max(sales)
maximo

14082.8

In [66]:
promedio = np.mean(sales)
promedio

3553.889071909316

In [65]:
cantidad = sales.size
cantidad

2823

In [69]:
suma = np.sum(sales)
suma

10032628.85

## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range

In [71]:
mascara_ventas = country== 'USA'
ventas_usa = data_type_default[mascara_ventas]
ventas_usa
cantidad_ventas_usa = len(ventas_usa)
print(f'La cantidad de ventas realizadas en USA es: {cantidad_ventas_usa}')

La cantidad de ventas realizadas en USA es: 1004


In [73]:
#Array slicing
sales_slicing = sales[6:11]
print(sales_slicing)

#Fancy indexing
indexes = range(6,11,1)
indexes_int = [6,7,8,9,10]
precio_ventas_1 = sales[indexes]
precio_ventas_2 = sales[indexes_int]
print(precio_ventas_1)
print(precio_ventas_2)



[2497.77 5512.32 2168.54 4708.44 3965.66]
[2497.77 5512.32 2168.54 4708.44 3965.66]
[2497.77 5512.32 2168.54 4708.44 3965.66]
