In [1]:
%run "../../../common/0_notebooks_base_setup.py"   

/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021_paula/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


En la práctica de la clase de hoy usaremos un dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

Ustedes tienen un subconjunto de los datos disponibles, que usaremos para resolver ejercicios de Numpy, Estadística y Probabilidad.

## Ejercicio 1
Leer los datos del archivo /M1/CLASE_03/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [1]:
## [BORRAR_PRESENCIAL]

import numpy as np
import seaborn as sns

# local:
data_location = '../Data/sales_data_sample_excercise.csv'

data_str = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data_str

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [2]:
data_int = np.genfromtxt(data_location, skip_header=1,delimiter='\t', dtype=int)
data_int

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,  2765,     5,  2003,    -1,    -1],
       [10134,  3884,     7,  2003,    -1,    -1],
       ...,
       [10386,  5417,     3,  2005,    -1,    -1],
       [10397,  2116,     3,  2005,    -1,    -1],
       [10414,  3079,     5,  2005,    -1,    -1]])

In [3]:
data_float = np.genfromtxt(data_location,skip_header=1, delimiter='\t', dtype=float)
data_float

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

## Ejercicio 2

Ahora queremos simular datos que representen las precios de ventas de USA en el mismo período, usando una distribución normal.

¿Qué parámetros tiene esa distribución?

Generar 100 datos simulados.

In [8]:
sales_vector_str = data_str[:,1]
sales_vector = sales_vector_str.astype(float)
print(sales_vector)

[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]


In [14]:
country_vector = data_str[:,-1]

ventas_mask = country_vector == 'USA'
precio_en_USA = sales_vector[ventas_mask]
precio_en_USA

array([2871.  , 3746.7 , 5205.27, ..., 1506.96, 4080.72, 3079.44])

In [24]:
media_sales =np.mean(precio_en_USA)
print(f'Media: {media_sales}')
print(f'Mediana: {np.median(precio_en_USA)}')
print(f'Rango: {max(sales_vector)-min(precio_en_USA)}')
desvio_sales = np.std(precio_en_USA)
print(f'Desvio: {desvio_sales}')

Media: 3613.5287151394423
Mediana: 3236.06
Rango: 13541.66
Desvio: 1879.9971929724536


In [23]:
random_generator = np.random.default_rng()
size_sample = 100
random_uniform_cont_data = random_generator.normal(loc=media_sales, scale=desvio_sales,size = size_sample)


## Ejercicio 3

Agregando a los datos originales los datos simulados en el punto anterior, calcular: 
* Media
* Mediana
* Rango
* Desvío estandard

Y comparar con el conjunto sin datos simulados

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

In [26]:
all_USA_data = np.concatenate((precio_en_USA,random_uniform_cont_data))
media_all = np.mean(all_USA_data)
print(f'Media: {media_all}')
print(f'Mediana: {np.median(all_USA_data)}')
print(f'Rango: {max(all_USA_data)-min(all_USA_data)}')
desvio_all = np.std(all_USA_data)
print(f'Desvio: {desvio_sales}')



Media: 3583.9486596712914
Mediana: 3243.13
Rango: 15870.036903329088
Desvio: 1879.9971929724536


## Ejercicio 4

Ahora queremos simular datos que representen las precios de ventas de USA en el mismo período, usando una distribución uniforme.

¿Qué parámetros tiene esa distribución?

Generar 100 datos simulados.

## Ejercicio 5

Agregando a los datos originales los datos simulados en el punto anterior, calcular: 
* Media
* Mediana
* Rango
* Desvío estandard

Y comparar con el conjunto sin datos simulados.

## Ejercicio 6

¿Cuál de las dos imputaciones de datos preservó mejor la distribución original?

In [10]:
import seaborn as sns

def distribution_plotter(data, label, color = 'steelblue',
                         bin_width=200):    
    sns.set(rc={"figure.figsize": (7, 5)})
    sns.set_style("white")    
    dist = sns.histplot(data, stat = 'count', kde = False, 
                        line_kws = {'linewidth':5}, 
                        binwidth = bin_width,
                       color = color)    
    dist.set_title('Distribucion ' + label + '\n', fontsize = 16)
    
    
